translations = {
  "1-bingo-chart": "1 bingo chart",
  "bingo-charts": "bingo charts",
  "about-text": "mikkoreinikainen.fi/esc-bingo",
};

items = [
  "A creepy smile",
  "The stage and the outfit blend in",
  "Very emotional singing",
  "A huge instrument onstage",
  "Modulation",
  "Flames",
  "Fireworks",
  "Finnish flag",
  "Flirting",
  "Wind maschine",
  "Revealing clothing",
  "Singing with eyes closed",
  "The singer has an instrument",
  "A kiss",
  "A sixpack",
  "The singing voice is way too high or low",
  "The hosts make an awkward joke",
  "A badly hidden political statement",
  "Dancing boys / girls",
  "Dancers lift the singer in the air",
  "A singer takes off a coat. He has a t-shirt underneath",
  "A singer takes off a dress or a coat. She has a miniskirt underneath",
  "The singer winks at the camera",
  "A huge train (in a dress or coat)",
  "The performers are standing in a line, the ones in the back are moving their hands",
  "The singer is barefoot",
  "A dancer has a jacket or vest but no shirt",
  "The singer plays for a second and forgets their instrument",
  "The singer has such a short skirt that it looks like a shirt",
  "The loser is trying to smile cheerily backstage",
  "The singer’s neckline reaches their navel",
  "The singer is in a costume (like a career or fairytale character)",
  "A flying kiss",
  "The person giving points talks with the hosts for too long",
  "The commentator tells that an artist has designed their own costume",
  "Dancers come towards the performer, who pushes them away",
  "A singer has wings",
  "The verse is in another language, the chorus in English",
  "Impressive tights",
  "Scifi theme",
  "Minority rights represented",
  "The song lyrics include the word Europe",
  "A strange instrument",
  "Clothing that prevents movement",
  "The dancers have a baffling choreography",
  "Someone says the night is ‘amazing’ or ‘wonderful’",
  "A previous Eurovision winner giving points",
  "A sexist joke",
  "A jump",
  "A country gives 12 points to its neighbor",
  "The song’s tempo changes",
  "A singer is nearly in tears",
  "A national dress or something similar",
  "The host changes clothes",
  "Pitchy singing",
  "Bad English",
  "The performance is embarrassingly bad/weird",
  "The performance highlights patriotism",
  "A very sexual performance",
  "The song is an earworm",
  "The staging overshadows the song",
  "The world will be saved / let’s save the world",
  "Trying to hype up the audience",
  "The light show could cause an epilepsy warning",
  "A smoke machine",
  "An impressive guitar solo",
  "A falling video floor",
  "The singer is a former child star",
  "A very wide stance",
  "The singer has represented the same country before",
  "The people at home are still awake when the hosts say ’start voting now’",
  "A cute dog, small animal or a stuffed animal",
  "Very strange shoes",
  "The song is in a language that no one recognizes",
  "The host are saying the same thing at the same time",
  "The song has folk elements",
  "A violin on stage",
  "The lyrics mention a bird or flying",
  "The artist has made the song themselves",
  "The body is still but the hands are dancing",
  "Text on stage",
  "The host is singing",
  "Rapping or talking in the song",
  "Really weird lyrics",
  "You can see the singer’s thonsils",
  "The singer is singing on their knees",
  "Singing or talking about dreams",
  "A planet or a star",
  "Fake shooting",
  "Someone disturbs the performance/hosts or someone makes a mistake",
  "Water elements onstage",
  "Devil theme or flames of hell",
  "pornographic imagery",
  "artist's clothes have very little fabric",
  "performers pose like statues",
  "shocking facial expression",
  "acrobatic jump or leap",
  "reference to Christianity",
  "performer runs",
  "flag as part of clothing",
  "a mythological or historical character",
  "a kick",
  "clear symbolism",
  "a funny hat",
  "tricky camera angles",
  "performer has bare feet",
  "performer has wings",
  "breaking gender norms",
  "intentional tastelessness",
  "bare buttocks",
  "cultural appropriation",
  "a mask",
  "glittering clothes",
  "gender norms are broken in a new way",
  "the performance is deliberately tasteless",
  "someone could be offended by this",
  "the performance radiates self-destructiveness",
  "female outfit erases all femininity",
  "rhythmic gymnastics outfit",
  "a really intense gaze",
  "all-white outfit or stage design",
  "someone is being searched for",
  "stage prop made of an unusual material",
  "the stage is used in a new way",
  "really warm clothing",
  "a magnificent hand gesture",
  "something completely weird on stage",
  "sparkling clothes",
  "someone is carrying someone",
  "a wink",
  "devil theme",
  "oops, that is really porn-y",
  "less than 1/4 m² of fabric on the performer",
  "shocking facial expression",
  "greetings to mom or family",
  "singer is tied up or otherwise unable to move",
  "accessory covering the eyes",
  "presenter messes up lines or freezes",
  "we're all one big family",
  "pseudo-artistic",
  "Christian reference",
  "there is running in the performance",
  "climate change theme",
  "amazing hairstyle",
  "flag is used as or in clothing",
  "outrageous shoes",
  "exaggerated symbolism",
  "a kick",
  "mythological or historical figure",
];
