translations = {
  "1-bingo-chart": "1 bingoruudukko",
  "bingo-charts": "bingoruudukkoa",
  "about-text": "mikkoreinikainen.fi/euroviisubingo"
}

items = ["creepy hymy",
  "lavaste ja vaate sulautuvat toisiinsa",
  "sielunkurotus",
  "lavalla valtava soitin",
  "kuhertelua",
  "modulaatio",
  "lieskoja",
  "ilotulituksia",
  "Suomen lippu",
  "tuulikone",
  "niukka vaatetus",
  "laulamista silmät kiinni",
  "laulajalla soitin",
  "suudelma",
  "sixpack",
  "aivan liian korkea/matala lauluääni",
  "juontajien väkinäistä vitsailua",
  "huonosti peitetty poliittinen kannanotto",
  "tanssijoita",
  "tanssijat nostavat laulajan ilmaan",
  "Laulaja riisuu takin. Alla on hihaton paita.",
  "Laulaja riisuu pitkän mekon tai takin. Alla on minihame.",
  "Laulaja iskee silmää kameralle",
  "valtava laahus",
  "esiintyjät jonossa, takana olevista näkyy huitovat kädet",
  "esiintyjä on paljain jaloin",
  "tanssijalla on takki tai liivi ilman paitaa",
  "laulaja soittaa pari säveltä ja unohtaa sitten instrumentin",
  "Laulajalla niin lyhyt hame, että se vaikuttaa paidalta.",
  "Takahuoneessa häviäjä yrittää hymyillä reippaasti.",
  "Laulajan kaula-aukko ulottuu napaan asti",
  "laulajalla on rooliasu (esim. ammatti tai satuhahmo)",
  "lentosuukko",
  "pisteiden antaja jää juttelemaan liian pitkään juontajan kanssa",
  "suomenkielisessä tekstityksessä on kökköjä käännöksiä",
  "juontaja kertoo, että artisti on itse suunnitellut pukunsa",
  "tanssijat tulevat laulajan luokse ja tämä tönäisee heidät pois",
  "laulajalla on siivet",
  "omankielinen säkeistö, englannikielinen kertsi",
  "mieleenjäävät sukkahousut",
  "scifi-teemaa",
  "vähemmistöjen oikeudet esillä",
  "laulun sanoissa mainitaan sana 'Eurooppa'",
  "erikoinen instrumentti",
  "vaate joka estää liikkumisen",
  "tanssijoilla käsittämätön koreografia",
  "joku sanoo illan olevan 'amazing' tai 'wonderful'",
  "aikaisempi euroviisuvoittaja jakaa pisteitä",
  "seksistinen vitsi",
  "hyppy tai loikka",
  "maa antaa parhaat pisteet naapurimaalleen",
  "laulun tempo vaihtuu yhtäkkiä",
  "laulaja liikuttuu ainakin lähes kyyneliin",
  "kansallispuku tai jotain sinnepäin",
  "juontaja vaihtaa vaatteita",
  "epävireistä laulua",
  "huonoa englantia",
  "esitys aiheuttaa syvää myötähäpeää",
  "isänmaallisuutta korostava esitys",
  "seksiä tihkuva esitys",
  "laulu aiheuttaa korvamadon",
  "laulu jää lavashown varjoon",
  "maailma pelastuu / pelastakaa maailma",
  "yritys nostattaa yleisöä",
  "valoshow aiheuttaa epilepsiavaaran",
  "savukone",
  "näyttävä kitarasoolo",
  "putoava videolattia",
  "tanssija käpälöi laulajaa",
  "laulajo on entinen lapsitähti",
  "merkittävän leveä haara-asento",
  "laulaja on edustanut maataan euroviisuissa ennenkin",
  "kotikatsomo on yhä hereillä, kun sanotaan 'start voting now'",
  "söpö koira, pehmolelu tai pikkueläin",
  "erittäin erikoiset kengät",
  "laulussa käytetään kaikille tuntematonta kieltä",
  "juontajat puhuvat kuorossa",
  "kappaleessa on kansanmusiikin piirteitä",
  "lavalla viulu",
  "lyriikoissa mainitaan lintu tai lentäminen",
  "artisti on itse tehnyt kappaleensa",
  "kroppa paikallaan, kädet tanssivat",
  "tekstiä lavalla",
  "juontaja laulaa",
  "biisi jää lavashown varjoon",
  "räppiä tai puhetta kesken laulun",
  "täysin käsittämätön lyriikka",
  "käsittämätön suomennos",
  "nielurisat näkyvät",
  "artisti laulaa polvillaan",
  "puhutaan tai lauletaan unelmista",
  "nähdään taivaankappale",
  "ammutaan leikisti",
  "käsivarret ja jalat kokonaan piilossa",
  "viuhahdus tai moka",
  "lavashowssa näkyy vettä",
  "paholaisteema tai helvetin lieskat",
  "pornokuvastoa",
  "pääesiintyjän vaatteeseen ei ole tuhlattu kangasta",
  "esiintyjät leikkivät patsaita",
  "järkyttävä ilme",
  "akrobaattinen hyppy tai loikka",
  "viittaus kristinuskoon",
  "esityksessä juostaan",
  "lippu osana vaatetusta",
  "mytologian tai historian hahmo",
  "potku",
  "selkeää symboliikkaa",
  "hassu hattu",
  "kuvakulmilla kikkailua",
  "esiintyjällä paljaat jalat",
  "esiintyjällä siivet",
  "rikotaan sukupuolinormeja",
  "tarkoituksista mauttomuutta",
  "paljaat pakarat",
  "kulttuurista omimista",
  "naamio",
  "kimaltelevat vaatteet",
]